name: Testes e Cobertura

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build, Testes e Jacoco
        working-directory: ./appwebsenai
        run: mvn clean verify

      - name: Upload cobertura para Codecov
        uses: codecov/codecov-action@v4
        with:         
          files: ./target/site/jacoco/jacoco.xml
          flags: unittests
